language: r
r:
  - bioc-release
  - bioc-devel
sudo: false
cache: packages
warnings_are_errors: false
before_install:
  - tlmgr install index
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix
